###############################################################################
# Multi-Camera Robot Hardware Manifest (Strict Serial-Only Layout)
################################################################################

cameras:
  - "25251937.yaml"
  - "25251936.yaml"
  - "25251947.yaml"
